"""
Tool: chem_features
Generated by Tool Builder Agent

Standardizes molecules and computes chemical features from SMILES columns. Supports Morgan fingerprints, RDKit descriptors, and physicochemical properties. Handles multiple SMILES columns and flexible input formats.

Examples:
1. chem_features('compounds_dataset', 'smiles', 'compound_features', features='morgan,physchem', radius=3, n_bits=2048)
2. chem_features('drug_data', ['smiles_1', 'smiles_2'], 'drug_descriptors', features='rdkit,physchem', standardize=False)

Data Inputs: Dataset (name/dict/CSV string) with SMILES columns
Data Outputs: Feature table with computed chemical descriptors saved to out_dataset
"""

import numpy as np
import pandas as pd
import pyarrow as pa
from typing import Any

# Tool implementation
def chem_features(dataset, smiles_cols, out_dataset, features='morgan,physchem', radius=2, n_bits=1024, standardize=True, *, db, config) -> str:
    """
    Standardizes molecules and computes chemical features from SMILES columns.
    
    Args:
        dataset: Dataset name (string), dict-like object, or CSV-like string
        smiles_cols: Single column name or list of column names containing SMILES
        out_dataset: Name for output dataset
        features: Comma-separated string or list of features ('morgan', 'rdkit', 'physchem')
        radius: Morgan fingerprint radius (default: 2)
        n_bits: Morgan fingerprint bits (default: 1024)
        standardize: Whether to standardize molecules (default: True)
    
    Returns:
        Summary string of feature computation results
    """
    import pandas as pd
    import numpy as np
    from rdkit import Chem
    from rdkit.Chem import Descriptors, rdMolDescriptors
    from rdkit.Chem.rdMolStandardize import rdMolStandardize
    import warnings
    warnings.filterwarnings('ignore')
    
    try:
        # Handle input dataset
        if isinstance(dataset, str):
            if ',' in dataset or '\n' in dataset:
                # CSV-like string
                from io import StringIO
                df = pd.read_csv(StringIO(dataset))
            else:
                # Dataset name
                df = db.get_table(dataset).to_pandas()
        else:
            # Dict-like object
            df = pd.DataFrame(dataset)
        
        # Handle smiles_cols parameter (accept both smiles_cols and smiles_col)
        if isinstance(smiles_cols, str):
            smiles_columns = [smiles_cols]
        else:
            smiles_columns = list(smiles_cols)
        
        # Handle features parameter
        if isinstance(features, str):
            feature_list = [f.strip().lower() for f in features.split(',')]
        else:
            feature_list = [f.lower() for f in features]
        
        # Validate features and warn about unknown ones
        valid_features = {'morgan', 'rdkit', 'physchem'}
        unknown_features = set(feature_list) - valid_features
        if unknown_features:
            print(f"Note: Ignoring unknown feature types: {', '.join(unknown_features)}")
        
        feature_list = [f for f in feature_list if f in valid_features]
        
        if not feature_list:
            return "Error: No valid feature types specified. Available: morgan, rdkit, physchem"
        
        # Initialize result dataframe
        result_df = df.copy()
        
        # Process each SMILES column
        total_molecules = 0
        standardized_count = 0
        failed_count = 0
        
        for smiles_col in smiles_columns:
            if smiles_col not in df.columns:
                print(f"Warning: Column '{smiles_col}' not found in dataset")
                continue
            
            col_suffix = f"_{smiles_col}" if len(smiles_columns) > 1 else ""
            molecules = []
            valid_indices = []
            
            # Process SMILES and standardize if requested
            for idx, smiles in enumerate(df[smiles_col]):
                if pd.isna(smiles) or smiles == '':
                    molecules.append(None)
                    continue
                
                try:
                    mol = Chem.MolFromSmiles(str(smiles))
                    if mol is None:
                        molecules.append(None)
                        failed_count += 1
                        continue
                    
                    if standardize:
                        try:
                            # Standardize molecule
                            normalizer = rdMolStandardize.Normalizer()
                            mol = normalizer.normalize(mol)
                            
                            # Remove fragments (keep largest)
                            uncharger = rdMolStandardize.Uncharger()
                            mol = uncharger.uncharge(mol)
                            
                            standardized_count += 1
                        except:
                            # If standardization fails, use original molecule
                            pass
                    
                    molecules.append(mol)
                    valid_indices.append(idx)
                    total_molecules += 1
                    
                except Exception as e:
                    molecules.append(None)
                    failed_count += 1
            
            # Compute features
            if 'morgan' in feature_list:
                # Morgan fingerprints
                morgan_fps = []
                for mol in molecules:
                    if mol is not None:
                        try:
                            fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
                            morgan_fps.append(list(fp))
                        except:
                            morgan_fps.append([0] * n_bits)
                    else:
                        morgan_fps.append([0] * n_bits)
                
                # Add Morgan fingerprint columns
                for i in range(n_bits):
                    result_df[f'morgan_{i}{col_suffix}'] = [fp[i] for fp in morgan_fps]
            
            if 'rdkit' in feature_list:
                # RDKit descriptors
                descriptor_names = [desc[0] for desc in Descriptors._descList]
                rdkit_features = {}
                
                for desc_name in descriptor_names:
                    desc_func = getattr(Descriptors, desc_name)
                    values = []
                    for mol in molecules:
                        if mol is not None:
                            try:
                                val = desc_func(mol)
                                values.append(val if not np.isnan(val) else 0.0)
                            except:
                                values.append(0.0)
                        else:
                            values.append(0.0)
                    result_df[f'rdkit_{desc_name}{col_suffix}'] = values
            
            if 'physchem' in feature_list:
                # Common physicochemical properties
                physchem_props = {
                    'mw': Descriptors.MolWt,
                    'logp': Descriptors.MolLogP,
                    'hbd': Descriptors.NumHDonors,
                    'hba': Descriptors.NumHAcceptors,
                    'tpsa': Descriptors.TPSA,
                    'rotatable_bonds': Descriptors.NumRotatableBonds,
                    'aromatic_rings': Descriptors.NumAromaticRings,
                    'heavy_atoms': Descriptors.HeavyAtomCount
                }
                
                for prop_name, prop_func in physchem_props.items():
                    values = []
                    for mol in molecules:
                        if mol is not None:
                            try:
                                val = prop_func(mol)
                                values.append(val if not np.isnan(val) else 0.0)
                            except:
                                values.append(0.0)
                        else:
                            values.append(0.0)
                    result_df[f'physchem_{prop_name}{col_suffix}'] = values
        
        # Save result
        db.save_table(out_dataset, result_df)
        
        # Create summary
        feature_counts = []
        if 'morgan' in feature_list:
            feature_counts.append(f"{n_bits} Morgan fingerprint bits")
        if 'rdkit' in feature_list:
            feature_counts.append(f"{len(Descriptors._descList)} RDKit descriptors")
        if 'physchem' in feature_list:
            feature_counts.append("8 physicochemical properties")
        
        summary = f"Chemical features computed for {len(smiles_columns)} SMILES column(s). "
        summary += f"Processed {total_molecules} molecules ({standardized_count} standardized, {failed_count} failed). "
        summary += f"Generated {', '.join(feature_counts)}. "
        summary += f"Results saved to '{out_dataset}' with {len(result_df.columns)} total columns."
        
        return summary
        
    except Exception as e:
        return f"Error computing chemical features: {str(e)}"

# Tool metadata for registration
TOOL_METADATA = {'name': 'chem_features', 'description': 'Standardizes molecules and computes chemical features from SMILES columns. Supports Morgan fingerprints, RDKit descriptors, and physicochemical properties. Handles multiple SMILES columns and flexible input formats.', 'examples': ["chem_features('compounds_dataset', 'smiles', 'compound_features', features='morgan,physchem', radius=3, n_bits=2048)", "chem_features('drug_data', ['smiles_1', 'smiles_2'], 'drug_descriptors', features='rdkit,physchem', standardize=False)"], 'data_inputs': 'Dataset (name/dict/CSV string) with SMILES columns', 'data_outputs': 'Feature table with computed chemical descriptors saved to out_dataset'}
