"""
Tool: generate_report
Generated by Tool Builder Agent

Compiles a human-readable report from provided sections (dataset names and/or text snippets). Accepts section entries as dataset names or literal text. Automatically includes key stats/figures if available, with simple captions. Saves the assembled report (markdown or HTML plus linked images) to out_dataset and returns a short summary with the artifact location.

Examples:
1. generate_report("Sales Analysis Q4", ["sales_data", "customer_metrics", "## Executive Summary\nQ4 showed strong growth across all segments."], "q4_sales_report", include_plots=True, notes="Prepared for board meeting")
2. generate_report("Data Quality Assessment", ["raw_data", "cleaned_data", "validation_results"], "quality_report", include_plots=False)

Data Inputs: title (str): Report title; sections (list): List of dataset names (strings) or literal text snippets; out_dataset (str): Name for saving the compiled report; include_plots (bool, optional): Whether to include plots/visualizations, defaults to True; notes (str, optional): Additional notes to include in report
Data Outputs: Saves compiled report as dataset with markdown/HTML content and linked images. Returns summary string with artifact location and report details.
"""

import numpy as np
import pandas as pd
import pyarrow as pa
from typing import Any

# Tool implementation
import os
import json
from datetime import datetime
import pandas as pd

def generate_report(title, sections, out_dataset, include_plots=True, notes=None, *, db, config) -> str:
    """
    Compiles a human-readable report from provided sections.
    
    Args:
        title: Report title
        sections: List of dataset names (strings) or literal text snippets
        out_dataset: Name for saving the compiled report
        include_plots: Whether to include plots/visualizations (default True)
        notes: Additional notes to include in report (optional)
    
    Returns:
        Summary string with artifact location and report details
    """
    
    if not isinstance(sections, list) or len(sections) == 0:
        return "Error: sections must be a non-empty list of dataset names or text snippets"
    
    if not title or not out_dataset:
        return "Error: title and out_dataset are required parameters"
    
    report_content = []
    report_content.append(f"# {title}\n")
    report_content.append(f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
    
    if notes:
        report_content.append(f"## Notes\n{notes}\n")
    
    section_count = 0
    dataset_sections = 0
    text_sections = 0
    plots_included = 0
    
    for i, section in enumerate(sections):
        section_count += 1
        
        # Check if section is a dataset name or literal text
        try:
            # Try to load as dataset
            dataset = db.get_table(section)
            dataset_sections += 1
            
            report_content.append(f"## Section {i+1}: Dataset '{section}'\n")
            
            # Add basic dataset info
            df = dataset.to_pandas()
            report_content.append(f"**Dataset Overview:**")
            report_content.append(f"- Rows: {len(df)}")
            report_content.append(f"- Columns: {len(df.columns)}")
            report_content.append(f"- Column names: {', '.join(df.columns.tolist())}\n")
            
            # Add sample data
            if len(df) > 0:
                report_content.append("**Sample Data (first 5 rows):**")
                sample_table = df.head().to_markdown(index=False)
                report_content.append(f"```\n{sample_table}\n```\n")
                
                # Add basic statistics for numeric columns
                numeric_cols = df.select_dtypes(include=['number']).columns
                if len(numeric_cols) > 0:
                    report_content.append("**Summary Statistics:**")
                    stats_table = df[numeric_cols].describe().to_markdown()
                    report_content.append(f"```\n{stats_table}\n```\n")
                
                # Generate simple plots if requested and output path available
                if include_plots and config.get('output_path'):
                    try:
                        import matplotlib.pyplot as plt
                        
                        # Create a simple histogram for first numeric column
                        if len(numeric_cols) > 0:
                            plt.figure(figsize=(8, 6))
                            plt.hist(df[numeric_cols[0]].dropna(), bins=20, alpha=0.7)
                            plt.title(f"Distribution of {numeric_cols[0]}")
                            plt.xlabel(numeric_cols[0])
                            plt.ylabel("Frequency")
                            
                            plot_filename = f"plot_{section}_{numeric_cols[0]}.png"
                            plot_path = os.path.join(config['output_path'], plot_filename)
                            plt.savefig(plot_path, dpi=150, bbox_inches='tight')
                            plt.close()
                            
                            report_content.append(f"**Visualization:**")
                            report_content.append(f"![Distribution of {numeric_cols[0]}]({plot_filename})")
                            report_content.append(f"*Figure: Distribution of {numeric_cols[0]} from dataset '{section}'*\n")
                            plots_included += 1
                            
                    except ImportError:
                        report_content.append("*Note: Plotting functionality not available*\n")
                    except Exception as e:
                        report_content.append(f"*Note: Could not generate plot - {str(e)}*\n")
            
        except Exception:
            # Treat as literal text
            text_sections += 1
            report_content.append(f"## Section {i+1}\n")
            report_content.append(f"{section}\n")
    
    # Compile final report
    final_report = "\n".join(report_content)
    
    # Create report metadata
    report_metadata = {
        "title": title,
        "generated_at": datetime.now().isoformat(),
        "total_sections": section_count,
        "dataset_sections": dataset_sections,
        "text_sections": text_sections,
        "plots_included": plots_included,
        "include_plots": include_plots,
        "notes": notes
    }
    
    # Save report as dataset
    report_data = pd.DataFrame([{
        "content": final_report,
        "metadata": json.dumps(report_metadata),
        "format": "markdown"
    }])
    
    try:
        db.save_table(out_dataset, report_data)
        
        # Also save as markdown file if output path available
        if config.get('output_path'):
            md_filename = f"{out_dataset}.md"
            md_path = os.path.join(config['output_path'], md_filename)
            with open(md_path, 'w', encoding='utf-8') as f:
                f.write(final_report)
        
        summary = f"Report '{title}' generated successfully with {section_count} sections "
        summary += f"({dataset_sections} datasets, {text_sections} text sections). "
        if plots_included > 0:
            summary += f"Included {plots_included} visualizations. "
        summary += f"Saved as dataset '{out_dataset}'"
        if config.get('output_path'):
            summary += f" and markdown file '{out_dataset}.md'"
        
        return summary
        
    except Exception as e:
        return f"Error saving report: {str(e)}"

# Tool metadata for registration
TOOL_METADATA = {'name': 'generate_report', 'description': 'Compiles a human-readable report from provided sections (dataset names and/or text snippets). Accepts section entries as dataset names or literal text. Automatically includes key stats/figures if available, with simple captions. Saves the assembled report (markdown or HTML plus linked images) to out_dataset and returns a short summary with the artifact location.', 'examples': ['generate_report("Sales Analysis Q4", ["sales_data", "customer_metrics", "## Executive Summary\\nQ4 showed strong growth across all segments."], "q4_sales_report", include_plots=True, notes="Prepared for board meeting")', 'generate_report("Data Quality Assessment", ["raw_data", "cleaned_data", "validation_results"], "quality_report", include_plots=False)'], 'data_inputs': 'title (str): Report title; sections (list): List of dataset names (strings) or literal text snippets; out_dataset (str): Name for saving the compiled report; include_plots (bool, optional): Whether to include plots/visualizations, defaults to True; notes (str, optional): Additional notes to include in report', 'data_outputs': 'Saves compiled report as dataset with markdown/HTML content and linked images. Returns summary string with artifact location and report details.'}
